### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by lipis** [AndrejsAbrickis/flag-icons#4]
Hi Andrejs,

It seems like this project is not supported anymore.

I own the https://www.npmjs.com/package/flag-icon-css (https://flagicons.lipis.dev/) but I want to rebrand it to just `flag-icons` as most of the people not using the built in CSS.

Would it be OK if I publish this project under https://www.npmjs.com/package/flag-icons? I think you can add me as admin on npmjs and then I can publish it there and deprecate my old one.. would that be OK?

**Comment by lipis** [comment]
Friendly reminder.. this is how you could add another owner..

```
npm owner add lipis flag-icons
```

**Comment by AndrejsAbrickis** [comment]
Done @lipis! Happy holidays! 🎅
